DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS npcs;
DROP TABLE IF EXISTS players;
CREATE TABLE players 
(
    id integer not null primary key autoincrement,
    account text not null,
    session integer not null,
    firstname text not null,
    lastname text not null,
    race text not null,
    gender text not null,
    profession text not null,
    level integer not null,
    hp integer not null,
    bp integer not null,
    mp integer not null,
    ep integer not null,
    strength integer not null,
    constitution integer not null,
    intelligence integer not null,
    dexterity integer not null,
    axe integer not null,
    dagger integer not null,
    unarmed integer not null,
    hammer integer not null,
    polearm integer not null,
    spear integer not null,
    staff integer not null,
    sword integer not null,
    archery integer not null,
    crossbow integer not null,
    sling integer not null,
    thrown integer not null,
    armor integer not null,
    dualWeapon integer not null,
    shield integer not null,
    bardic integer not null,
    conjuring integer not null,
    druidic integer not null,
    illusion integer not null,
    necromancy integer not null,
    sorcery integer not null,
    shamanic integer not null,
    spellcraft integer not null,
    summoning integer not null,
    focus integer not null,
    armorsmithing integer not null,
    tailoring integer not null,
    fletching integer not null,
    weaponsmithing integer not null,
    alchemy integer not null,
    lapidary integer not null,
    calligraphy integer not null,
    enchanting integer not null,
    herbalism integer not null,
    hunting integer not null,
    mining integer not null,
    bargaining integer not null,
    camping integer not null,
    firstAid integer not null,
    lore integer not null,
    pickLocks integer not null,
    scouting integer not null,
    search integer not null,
    stealth integer not null,
    traps integer not null,
    aeolandis integer not null,
    hieroform integer not null,
    highGundis integer not null,
    oldPraxic integer not null,
    praxic integer not null,
    runic integer not null,
    weight integer not null,
    x integer not null,
    y integer not null,
    z integer not null,
    direction real not null
);
--CREATE TABLE npcs
--(
--        
--);
--CREATE TABLE accounts
--(
--
--);
