// Filename:    game_objects.go
// Author:      Joseph DeVictoria
// Date:        Aug_30_2018

package main

type Pc struct {
	id             int32
	account_id     int32
	firstname      string
	lastname       string
	guild          string
	race           string
	gender         string
	face           string
	skin           string
	profession     string
	alive          bool
	plevel         int32
	dp             int32
	hp             int32
	maxhp          int32
	bp             int32
	maxbp          int32
	mp             int32
	maxmp          int32
	ep             int32
	maxep          int32
	strength       int32
	constitution   int32
	intelligence   int32
	dexterity      int32
	axe            int32
	dagger         int32
	unarmed        int32
	hammer         int32
	polearm        int32
	spear          int32
	staff          int32
	sword          int32
	archery        int32
	crossbow       int32
	sling          int32
	thrown         int32
	armor          int32
	dualweapon     int32
	shield         int32
	bardic         int32
	conjuring      int32
	druidic        int32
	illusion       int32
	necromancy     int32
	sorcery        int32
	shamanic       int32
	spellcraft     int32
	summoning      int32
	focus          int32
	armorsmithing  int32
	tailoring      int32
	fletching      int32
	weaponsmithing int32
	alchemy        int32
	lapidary       int32
	calligraphy    int32
	enchanting     int32
	herbalism      int32
	hunting        int32
	mining         int32
	bargaining     int32
	camping        int32
	firstaid       int32
	lore           int32
	picklocks      int32
	scouting       int32
	search         int32
	stealth        int32
	traps          int32
	aeolandis      int32
	hieroform      int32
	highgundis     int32
	oldpraxic      int32
	praxic         int32
	runic          int32
	head           string
	chest          string
	arms           string
	hands          string
	legs           string
	feet           string
	cloak          string
	necklace       string
	ringone        string
	ringtwo        string
	righthand      string
	lefthand       string
	zone           string
	x              float32
	y              float32
	z              float32
	direction      float32
}

type Npc struct {
	Id           int32
	Firstname    string
	Lastname     string
	Guild        string
	Race         string
	Gender       string
	Face         string
	Skin         string
	Profession   string
	Alive        bool
	Nlevel       int32
	Hp           int32
	Maxhp        int32
	Bp           int32
	Maxbp        int32
	Mp           int32
	Maxmp        int32
	Ep           int32
	Maxep        int32
	Strength     int32
	Constitution int32
	Intelligence int32
	Dexterity    int32
	Head         string
	Chest        string
	Arms         string
	Hands        string
	Legs         string
	Feet         string
	Cloak        string
	Righthand    string
	Lefthand     string
	Zone         string
	X            float32
	Y            float32
	Z            float32
	Direction    float32
}
